#!/bin/bash
set -euo pipefail

usage() {
    echo "Usage: $(basename "$0") <vm-name>"
    echo
    echo "Prepare a running VM to be used as a golden base image."
    echo
    echo "Cleans up instance-specific state (shell history, SSH host keys,"
    echo "caches, logs) then stops the VM. After this, the VM is ready to"
    echo "be cloned with: provision-vm.sh <new-vm> --base <vm-name>"
    echo
    echo "The VM must be running and have the guest agent available."
    exit 0
}

if [[ $# -ne 1 ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    usage
fi

VM_NAME="$1"

# Verify VM is running and guest agent is available
if ! tart exec "$VM_NAME" true 2>/dev/null; then
    echo "Error: Cannot reach guest agent for VM '$VM_NAME'. Is it running?"
    exit 1
fi

# Detect the non-admin user (first user in /Users that isn't admin, Shared, or .localized)
VM_USER=$(tart exec "$VM_NAME" ls /Users \
    | grep -v -E '^(admin|Shared|\.localized)$' \
    | head -1 || true)

echo "=== Preparing golden image: $VM_NAME ==="
[[ -n "$VM_USER" ]] && echo "  Detected user: $VM_USER"
echo ""

# --- Shell history ---
echo "[1/7] Clearing shell history..."
tart exec "$VM_NAME" sudo rm -f /Users/admin/.zsh_history /Users/admin/.bash_history
if [[ -n "$VM_USER" ]]; then
    tart exec "$VM_NAME" sudo rm -f "/Users/$VM_USER/.zsh_history" "/Users/$VM_USER/.bash_history"
fi
echo "      Done."

# --- SSH host keys (will be regenerated by provision-vm.sh on clone) ---
echo "[2/7] Removing SSH host keys..."
tart exec "$VM_NAME" sudo rm -f /etc/ssh/ssh_host_*
echo "      Done."

# --- SSH known_hosts ---
echo "[3/7] Clearing SSH known_hosts..."
tart exec "$VM_NAME" sudo rm -f /Users/admin/.ssh/known_hosts
if [[ -n "$VM_USER" ]]; then
    tart exec "$VM_NAME" sudo rm -f "/Users/$VM_USER/.ssh/known_hosts"
fi
echo "      Done."

# --- Homebrew cache ---
echo "[4/7] Cleaning Homebrew cache..."
tart exec "$VM_NAME" sudo -Hu "${VM_USER:-admin}" zsh -l -c 'brew cleanup --prune=all 2>/dev/null' || true
echo "      Done."

# --- System logs and caches ---
echo "[5/7] Clearing system logs and caches..."
tart exec "$VM_NAME" sudo rm -rf /var/log/asl/*.asl
tart exec "$VM_NAME" sudo rm -rf /Library/Logs/DiagnosticReports/*
tart exec "$VM_NAME" sudo rm -rf /tmp/*
echo "      Done."

# --- DHCP leases ---
echo "[6/7] Clearing DHCP leases..."
tart exec "$VM_NAME" sudo rm -f /var/db/dhcpclient/leases/* 2>/dev/null || true
echo "      Done."

# --- Stop VM ---
echo "[7/7] Stopping VM..."
tart stop "$VM_NAME"
echo "      Done."

echo ""
echo "========================================"
echo "  Golden image ready: $VM_NAME"
echo "========================================"
echo "  Clone with:"
echo "    ./provision-vm.sh <new-vm> --base $VM_NAME"
echo "========================================"
